# Generated by Django 3.1.2 on 2021-01-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_proof',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
