# Generated by Django 3.1.7 on 2021-04-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mechant',
        ),
    ]
