# Generated by Django 3.1.7 on 2021-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_auto_20210402_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_revunue',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('DECEMBER', 'December')], max_length=9),
        ),
    ]
