# Generated by Django 3.1.7 on 2021-04-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20210402_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechant',
            name='today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mechant',
            name='monthly_revunue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.monthly_revunue'),
        ),
    ]
