# Generated by Django 3.1.7 on 2021-04-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_auto_20210402_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechant',
            name='monthly_revunue',
        ),
        migrations.AddField(
            model_name='monthly_revunue',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchant.mechant'),
        ),
    ]
