# Generated by Django 3.1.7 on 2021-04-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0008_auto_20210402_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_revunue',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
