# Generated by Django 3.1.7 on 2021-04-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0009_monthly_revunue_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_revunue',
            name='no_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
