# Generated by Django 3.1.2 on 2021-01-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribedmaile'),
    ]

    operations = [
        migrations.CreateModel(
            name='prize_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('disccount', models.IntegerField(default=0)),
                ('prize', models.IntegerField(default=0)),
                ('product_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.products')),
            ],
        ),
    ]
