# Generated by Django 3.1.2 on 2021-01-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prize_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize_chart',
            name='orginal_prize',
            field=models.IntegerField(default=0),
        ),
    ]
